### PR TITLE
added a method to create a user in OIM

### PR DESCRIPTION
**Pull request by keeshendriks**

### CODE REVIEW

**Comment by keeshendriks** [comment]
Zou je deze pull request nog kunnen reviewen?

**Review by jrkoiter — CHANGES_REQUESTED** [review]
A few remarks before merging:

365: Put references in documentation to other keywords between backticks, and use the keyword name, not the method name. Put references to arguments between underscores. And please also document what is returned.
369: Error message not a valid sentence.
383: Use UserManagerConstants.AttributeName.USER_LOGIN.getId() instead of literal attribute name
386 - 391: Use UserManagerConstants for attribute names. And "LastNameOwn" is an implementation specific UDF I think? Should not be in this generic library.
396: Use UserManagerConstants for attribute names.
397: Use UserManagerConstants for attribute names, or if this is a custom attribute: put explanation and usage in keyword documentation on line 365.
400: Use UserManagerConstants for attribute names.

**Comment by keeshendriks** [comment]
Ik heb de code verbeterd zou je nogmaals kunnen kijken?

**Comment by keeshendriks** [comment]
is het zo wel goed?

**Review by jrkoiter — APPROVED** [review]

**Pull request merged**
